image: google/cloud-sdk

variables:
  NAME: waitlist-microservice

stages:
  - build
  - deploy

build-dev:
  stage: build
  variables:
    SERVICE_ACCOUNT: $DEV_GCP_DEPLOY_SERVICE_ACCOUNT
    PROJECT_ID: soundheart-dev-94cc1
    ENV: $SERVICES_DEV_ENV
    NPM_TOKEN: $NPM_TOKEN
  before_script:
    - echo $SERVICE_ACCOUNT | base64 --decode >> key.json
    - echo $ENV | base64 --decode >> .env.yml
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config set project $PROJECT_ID
  script:
    - gcloud builds submit . --config=cloudbuild.yml --substitutions=_NPM_TOKEN=$NPM_TOKEN
  tags:
    - docker
  only:
    - main

deploy-dev:
  stage: deploy
  variables:
    SERVICE_ACCOUNT: $DEV_GCP_DEPLOY_SERVICE_ACCOUNT
    PROJECT_ID: soundheart-dev-94cc1
    SECRET_YAML: $SERVICES_SECRET_DEV_YAML
  before_script:
    - echo $SERVICE_ACCOUNT | base64 --decode >> key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config set project $PROJECT_ID
    - echo $SECRET_YAML | base64 --decode >> k8s/secret.yaml
    - gcloud container clusters get-credentials event-driven-cluster --zone us-central1-c --project $PROJECT_ID
  script:
    - kubectl apply -f k8s/secret.yaml
    - helm upgrade $NAME k8s --install --set image.repository=gcr.io/$PROJECT_ID/$NAME --set image.tag=latest --set ingress.hosts[0].paths[0].path=/api/$NAME,ingress.hosts[0].host=dev.ateliahealth.com,ingress.hosts[0].paths[0].pathType=Prefix,ingress.tls[0].secretName=wildcard-tls,ingress.tls[0].hosts[0]=dev.ateliahealth.com
    - kubectl rollout restart deployment $NAME-k8s
    - kubectl describe deployment $NAME-k8s
  needs:
    - build-dev
  only:
    - main
  tags:
    - kubernetes
