steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'NPM_TOKEN=${_NPM_TOKEN}',
        '-t',
        'gcr.io/$PROJECT_ID/waitlist-microservice',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/waitlist-microservice']
